"""empty message

Revision ID: bed58c89239d
Revises: 35824ea5f44a
Create Date: 2023-06-26 10:14:52.027443

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed58c89239d'
down_revision = '35824ea5f44a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nickname', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint(None, ['nickname'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('nickname')

    # ### end Alembic commands ###
